from enum import Enum


class StorageErrorCode(str, Enum):
    INVALID_KEY = "INVALID_KEY"
    INVALID_URI = "INVALID_URI"
    OBJECT_NOT_FOUND = "OBJECT_NOT_FOUND"
    DOWNLOAD_URL_INVALID = "DOWNLOAD_URL_INVALID"
    DOWNLOAD_URL_EXPIRED = "DOWNLOAD_URL_EXPIRED"
    METADATA_MISMATCH = "METADATA_MISMATCH"
    BACKEND_UNAVAILABLE = "BACKEND_UNAVAILABLE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"


from data_analysis_agent.datasets.errors import StorageError
